# Generated by Django 5.0.2 on 2024-03-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_ball'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.RenameField(
            model_name='ball',
            old_name='velocity_x',
            new_name='radius',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='game',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='velocity_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='animationFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='ball',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='game.ball'),
        ),
        migrations.AddField(
            model_name='game',
            name='beginPos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='dirX',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='game',
            name='dirY',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='leftPlyrScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='maxScore',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='game',
            name='rightPlyrScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='speedBall',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='game',
            name='speedPlayer',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='ball',
            name='position_x',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ball',
            name='position_y',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AddField(
            model_name='game',
            name='leftPaddle',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='left_games', to='game.paddle'),
        ),
        migrations.AddField(
            model_name='game',
            name='rightPaddle',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='right_games', to='game.paddle'),
        ),
        migrations.AddField(
            model_name='game',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.screen'),
            preserve_default=False,
        ),
    ]
