# Generated by Django 5.0.2 on 2024-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_paddle_screen_delete_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paddle',
            name='height',
        ),
        migrations.RemoveField(
            model_name='paddle',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='paddle',
            name='width',
        ),
        migrations.AlterField(
            model_name='paddle',
            name='position_y',
            field=models.IntegerField(default=0.0),
        ),
    ]
